import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // 라이트 테마 (화이트 배경 + 오렌지/옐로우 포인트, 따소미 캐릭터 컬러와 맞춤)
        "on-tertiary-container": "#9C8768",
        "surface-container": "#FFF6E5",
        "on-error": "#FFFFFF",
        "secondary-container": "#FFC93C",
        "primary-fixed": "#FFE3CC",
        "primary-container": "#FFE3CC",
        "surface-container-lowest": "#F5F1E8",
        "secondary-fixed-dim": "#E0891F",
        "tertiary-fixed": "#FFE3CC",
        "on-primary-fixed-variant": "#8A4A1A",
        "inverse-on-surface": "#FFF6E5",
        "on-error-container": "#8A1F1F",
        "inverse-primary": "#F2762E",
        "on-secondary-container": "#5C3D00",
        tertiary: "#D9631F",
        background: "#FFFFFF",
        "on-background": "#3A2E1F",
        "on-surface": "#3A2E1F",
        "surface-container-low": "#FFFDF8",
        "surface-container-highest": "#FFE3AD",
        "outline-variant": "#E3D2AE",
        "surface-container-high": "#FFEFD0",
        secondary: "#F2762E",
        outline: "#D9C7A3",
        primary: "#F2762E",
        "on-secondary-fixed-variant": "#5C3D00",
        "on-primary": "#FFFFFF",
        "on-secondary-fixed": "#5C3D00",
        "surface-variant": "#FFF6E5",
        "primary-fixed-dim": "#FFC93C",
        "on-tertiary-fixed": "#3A2E1F",
        "on-primary-fixed": "#3A2E1F",
        surface: "#FFFFFF",
        "on-tertiary": "#3A2E1F",
        "tertiary-fixed-dim": "#D9631F",
        "tertiary-container": "#FFE3CC",
        "surface-dim": "#FFFBF3",
        "on-secondary": "#FFFFFF",
        "secondary-fixed": "#D9631F",
        "on-tertiary-fixed-variant": "#5C3D00",
        "inverse-surface": "#3A2E1F",
        "on-primary-container": "#8A4A1A",
        "on-surface-variant": "#6B5B45",
        error: "#E53935",
        "error-container": "#FFEBEE",
        "surface-tint": "#F2762E",
        "surface-bright": "#FFFFFF",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        md: "16px",
        sm: "8px",
        lg: "24px",
        base: "4px",
        xs: "4px",
        gutter: "16px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "data-mono": ["Geist", "monospace"],
        "body-base": ["Inter", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "data-mono": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
